### ISSUE TITLE
Datenbank Verbindung zu MainPage

### ISSUE THREAD

**Issue by TaliZohra** [luisewinzer/SE-Projekt#14]
- Tabelle in Datenbank für die Gräber anlegen
- Tabelle in MainPage aufrufen
- DeceasedPerson List erstellen
- Inhalte aus Tabelle in List einlesen

**Comment by luisewinzer** [comment]
Verbindung zur Datenbank hat trotz mehrfacher, unterschiedlicher Versuche nicht funktioniert. Daher Umgestaltung der MainPage (siehe entsprechendes Issue dazu)
