### ISSUE TITLE
Bugfix L-R-Screen

### ISSUE THREAD

**Issue by luisewinzer** [luisewinzer/SE-Projekt#8]
- Account erstellen funktioniert nicht: Datenbank?

**Comment by TaliZohra** [comment]
- Account erstellen funktioniert nicht: Datenbank? <-- ist jetzt gefixed

**Comment by TaliZohra** [comment]
Registrieren funktioniert immer noch nicht. :(

**Comment by luisewinzer** [comment]
Problem gefunden: Tabellenkopf muss angepasst werden in der Datenbank. Die deutschen Begriffe durch englische Begriffe (username, password) ersetzen.

**Comment by TaliZohra** [comment]
Problem anders angegangen. Zugriff auf Datenbank über extra Klasse.
Datenbank wird dadurch korrekt in den bin/Debug geladen. Führt kein dauerhaftes speichern durch aber für die Runtime.
